# profiler y el wdt
_profiler:
  resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
  prefix:   /_profiler

_wdt:
  resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
  prefix:   /_wdt

_configurator:
  resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
  prefix:   /_configurator


Other_routes_dev:
  resource: ../../app/config/routing_dev.yml

BaseMainBundleRoutes:
  resource: "@O2WBundle/Resources/config/routing.yml"
