# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


O2WBundle:
  resource: "@O2WBundle/Controller"
  type:     annotation

_imagine:
    resource: .
    type:     imagine




# Catch all route
slug_route:
  pattern: /{slug}
  defaults: { _controller: O2WBundle:Slug:find }
  requirements:
    slug : .*

