<?php

namespace O2W\O2WBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseNodeRepository extends EntityRepository
{
}